// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfoyTakipAPI.Models;

#nullable disable

namespace PortfoyTakipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922072004_VeriKurtarmaSync")]
    partial class VeriKurtarmaSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalkaArzKonsorsiyum", b =>
                {
                    b.Property<int>("HalkaArzlarId")
                        .HasColumnType("int");

                    b.Property<int>("KonsorsiyumlarId")
                        .HasColumnType("int");

                    b.HasKey("HalkaArzlarId", "KonsorsiyumlarId");

                    b.HasIndex("KonsorsiyumlarId");

                    b.ToTable("HalkaArzKonsorsiyum");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.HalkaArz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ArzBuyukluguTL")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BorsaKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("BorsaVerisiSonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<string>("DagitimYontemi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FinansalBorcluluk")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FinansalCiroArtisi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FinansalKarMarji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FiyatGecmisiJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FonKullanimYerleriJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GerceklesenKatilimciSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("GuncelFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GunlukDegisimYuzdesi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HalkaAciklikOrani")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("IskontoOrani")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("KatilimEndeksineUygunMu")
                        .HasColumnType("bit");

                    b.Property<decimal>("LotFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sektor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SirketOzeti")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Statu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaahhutlerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TalepToplamaBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TalepToplamaBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamDagilacakLot")
                        .HasColumnType("int");

                    b.Property<string>("ZamanGecmisiJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HalkaArzlar");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.Konsorsiyum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Konsorsiyumlar");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.KullaniciGiris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenBitisSuresi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.Varlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AlisFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Varliklar");
                });

            modelBuilder.Entity("HalkaArzKonsorsiyum", b =>
                {
                    b.HasOne("PortfoyTakipAPI.Models.HalkaArz", null)
                        .WithMany()
                        .HasForeignKey("HalkaArzlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfoyTakipAPI.Models.Konsorsiyum", null)
                        .WithMany()
                        .HasForeignKey("KonsorsiyumlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
