// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfoyTakipAPI.Models;

#nullable disable

namespace PortfoyTakipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902104857_HalkaArzSektorVeKatilimEklemeleri")]
    partial class HalkaArzSektorVeKatilimEklemeleri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfoyTakipAPI.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.HalkaArz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorsaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GerceklesenKatilimciSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("KatilimEndeksineUygunMu")
                        .HasColumnType("bit");

                    b.Property<string>("KonsorsiyumLideri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LotFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sektor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TalepToplamaBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TalepToplamaBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamDagilacakLot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HalkaArzlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorsaKodu = "MCARD",
                            KatilimEndeksineUygunMu = false,
                            LotFiyati = 25.00m,
                            SirketAdi = "Metropol Kurumsal Hizmetler",
                            Statu = "İşlem Gören",
                            TalepToplamaBaslangic = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TalepToplamaBitis = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplamDagilacakLot = 30000000
                        },
                        new
                        {
                            Id = 2,
                            BorsaKodu = "TKNJI",
                            KatilimEndeksineUygunMu = false,
                            LotFiyati = 42.50m,
                            SirketAdi = "Teknoloji Gelecek A.Ş.",
                            Statu = "Talep Toplayan",
                            TalepToplamaBaslangic = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TalepToplamaBitis = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplamDagilacakLot = 15000000
                        },
                        new
                        {
                            Id = 3,
                            BorsaKodu = "ENRGY",
                            KatilimEndeksineUygunMu = false,
                            LotFiyati = 18.20m,
                            SirketAdi = "Yeşil Enerji Üretim",
                            Statu = "Yaklaşan",
                            TalepToplamaBaslangic = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TalepToplamaBitis = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplamDagilacakLot = 55000000
                        });
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.KullaniciGiris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenBitisSuresi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PortfoyTakipAPI.Models.Varlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AlisFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Varliklar");
                });
#pragma warning restore 612, 618
        }
    }
}
