events { }

http {
    server {
        listen 80;

        location / {
            # Docker içinden, senin Windows (host) makinenin 8080 portuna giden köprü
            proxy_pass http://host.docker.internal:8080;
        }
    }
}